version: '3'

services:
  haproxy_cloudflare_jwt_validator:
    build: ../
    image: haproxy_cloudflare_jwt_validator:latest
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ../src/jwtverify.lua:/usr/local/share/lua/5.3/jwtverify.lua
      - ../src/base64.lua:/usr/local/share/lua/5.3/base64.lua
    depends_on:
      - debug_http_listener
      - cloudflare_mock

  debug_http_listener:
    image: mendhak/http-https-echo

  cloudflare_mock:
    image: python:2.7
    volumes:
      - ./cloudflare_mock/cdn-cgi:/cdn-cgi
    expose:
      - "80"
    ports:
      - "8081:80"
    command: python -m SimpleHTTPServer 80